name: Install and Build (Composite)
description: Installs and builds WooCommerce.
inputs:
  working_directory:
    required: false
    description: The directory to target.
    default: ./

runs:
  using: "composite"
  steps:
    - name: Install
      uses: ./../install

    - name: Run build
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: pnpm -- turbo run build --filter=woocommerce
