name: Cache Dependencies and builds (Composite)
description: Creates and restores caches for dependencies and builds.
inputs:
  workflow_cache:
    required: true
    description: The workflow cache key.
  workflow_name:
    required: true
    description: The name of the workflow.

runs:
  using: "composite"
  steps:
    - name: Dependency and build caching
      uses: actions/cache@v3
      id: cache-deps
      with:
        path: |
          ~/.pnpm-store
          ~/.local/share/pnpm/store
          ~/.cache/composer/files
        key: ${{ runner.os }}-${{ inputs.workflow_name }}-${{ inputs.workflow_cache }}-${{ hashFiles('**/composer.lock', '**/pnpm-lock.yaml') }}
