name: 'CI'
on: 
  pull_request:
  push:
    branches:
      - 'trunk'
      - 'release/*'
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
jobs:
    project-matrix:
      name: 'Build Project Matrix'
      runs-on: 'ubuntu-20.04'
      outputs:
        matrix: ${{ steps.project-matrix.outputs.matrix }}
      steps:
        - uses: 'actions/checkout@v3'
          name: 'Checkout'
          with:
            fetch-depth: 0
        - uses: './.github/actions/setup-woocommerce-monorepo'
          name: 'Setup Monorepo'
          with:
            install: false
        - uses: actions/github-script@v6
          id: 'project-matrix'
          name: 'Build Matrix'
          with:
            script: |
              let baseRef = ${{ toJson( github.base_ref ) }};
              if ( baseRef ) {
                baseRef = 'origin/' + baseRef;
              }
              const buildCIMatrix = require( './.github/workflows/scripts/build-ci-matrix' );
              core.setOutput( 'matrix', JSON.stringify( await buildCIMatrix( baseRef ) ) );
    project-task-matrix:
      name: '${{ matrix.projectName }} - ${{ matrix.taskName }}'
      runs-on: 'ubuntu-20.04'
      needs: 'project-matrix'
      strategy:
        fail-fast: false
        matrix:
          include: ${{ fromJSON( needs.project-matrix.outputs.matrix ) }}
      steps:
        - uses: 'actions/checkout@v3'
          name: 'Checkout'
        - uses: './.github/actions/setup-woocommerce-monorepo'
          name: 'Setup Monorepo'
          with:
            install-filters: '${{ matrix.projectName }}...'
            build-filters: '${{ matrix.projectName }}'
        - name: 'Dump Test ENV Vars'
          env: ${{ matrix.testEnvVars }}
          run: 'printenv'
        - name: 'Prepare Test Environment'
          if: ${{ matrix.needsTestEnvironment }}
          env: ${{ matrix.testEnvVars }}
          run: 'pnpm --filter="${{ matrix.projectName }}" test:env:start'
        - name: 'Lint'
          if: ${{ matrix.runLint }}
          run: 'pnpm --filter="${{ matrix.projectName }}" lint'
        - name: 'Test - JS'
          if: ${{ matrix.runJSTests }}
          run: 'pnpm --filter="${{ matrix.projectName }}" test:js'
        - name: 'Test - PHP'
          if: ${{ matrix.runPHPTests }}
          run: 'pnpm --filter="${{ matrix.projectName }}" test:php'
        - name: 'E2E'
          if: ${{ matrix.runE2E }}
          run: 'pnpm --filter="${{ matrix.projectName }}" e2e'
