name: Performance metrics

on:
    pull_request:
        paths:
            - 'plugins/woocommerce/**'
            - '.github/workflows/pr-assess-performance.yml'

concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    build:
        name: Evaluate performance metrics
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write

        steps:
            - uses: actions/checkout@v4
              name: Checkout (current - ${{ github.head_ref }})
              with:
                fetch-depth: 0

            - uses: ./.github/actions/setup-woocommerce-monorepo
              name: Install Monorepo
              with:
                install: '@woocommerce/plugin-woocommerce...'
                build: '@woocommerce/plugin-woocommerce'
                build-type: 'full'
                pull-playwright-cache: true
                pull-package-deps: '@woocommerce/plugin-woocommerce'

            - name: Start Test Environment
              run: 'pnpm --filter="@woocommerce/plugin-woocommerce" env:test'

            - name: Measure performance (editor@${{ github.sha }})
              env:
                WP_ARTIFACTS_PATH: 'tools/compare-perf/artifacts/'
                RESULTS_ID: 'editor__${{ github.sha }}__round-1'
              run: 'pnpm --filter="@woocommerce/plugin-woocommerce" test:metrics editor'
            - name: Measure performance (product-editor@${{ github.sha }})
              env:
                WP_ARTIFACTS_PATH: 'tools/compare-perf/artifacts/'
                RESULTS_ID: 'product-editor__${{ github.sha }}__round-1'
              run: 'pnpm --filter="@woocommerce/plugin-woocommerce" test:metrics product-editor'
              
            - name: Checkout (baseline - ${{ github.base_ref }})
              run: |
                git reset --hard
                git checkout ${{ github.base_ref }}

            - name: Rebuild
              run: |
                pnpm install --filter='@woocommerce/plugin-woocommerce...' --frozen-lockfile --config.dedupe-peer-dependents=false
                pnpm --filter='@woocommerce/plugin-woocommerce' build

            
            # Calculating/Printing results
            # Publish to CodeVitals (see .github/workflows/scripts/run-metrics.sh)
            # TODO: caching and downloading artifacts with already performed measures.
