name: WooCommerce Beta Tester Release
permissions: {}

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'The version number for the release'
                required: true

jobs:
    release:
        name: Run release scripts
        runs-on: ubuntu-20.04
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                  install: '@woocommerce/plugin-woocommerce'
                  build: '@woocommerce/plugin-woocommerce'

            - name: Lint
              working-directory: plugins/woocommerce-beta-tester
              run: composer run phpcs

            - name: Build WooCommerce Beta Tester Zip
              working-directory: plugins/woocommerce-beta-tester
              run: pnpm build:zip
