name: WooCommerce Beta Tester Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'The version number for the release'
                required: true

jobs:
    release:
        name: Run release scripts
        runs-on: ubuntu-20.04
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v3

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo

            - name: Create release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ inputs.version }}
                  release_name: Release ${{ inputs.version }}
                  draft: false
                  prerelease: false

            - name: Build WooCommerce Beta Tester Zip
              working-directory: plugins/woocommerce-beta-tester
              run: pnpm build:zip

            - name: Upload files to release
              uses: actions/upload-release-asset@v2

              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: woocommerce-beta-tester.zip
                  asset_name: woocommerce-beta-tester.zip
