name: "Validate Security Repo PR"
on:
  pull_request_target:
permissions: {}
jobs:
  update_base_and_add_comment:
    name: Update base and add comment
    if: github.event.pull_request.base.ref == 'security'
    runs-on: ubuntu-20.04
    permissions:
      pull-requests: write
    steps:
      - name: Update base
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.update( {
              pull_number: context.payload.pull_request.number,
              owner: context.payload.pull_request.base.repo.owner.login, 
              repo: context.payload.pull_request.base.repo.name,
              base: 'trunk',
            } );
      - name: Add comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Hi @${{ github.event.pull_request.user.login }},
            
            Thanks for this pull request. I've updated the target of this PR to `trunk`. Pull requests in this repository should target `trunk` until you know which release branch you'd like to target. Please see the [README](https://github.com/Automattic/woocommerce#preparing-a-security-fix) at the root of the repo for more information.
