name: Setup, build and cache project
on: pull_request
permissions: {}

jobs:
    build-setup-cache:
        name: Setup dependencies, build, cache
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo

            - name: Trigger dependent workflows
              uses: peter-evans/repository-dispatch@v1
              with:
                  token: ${{ secrets.PAT_TOKEN_REPO_DISPATCH }}
                  repository: ${{ github.repository }}
                  event-type: build-and-cache-complete
                  client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
