name: Set up dependencies, build project, cache outputs.

permissions: {}

jobs:
    build-and-cache:
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.user.login != 'github-actions[bot]' }}
        name: Setup, build, cache
        runs-on: ubuntu-20.04
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v3

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo

            - name: Trigger dependent workflows
              if: success()
              uses: peter-evans/repository-dispatch@v1
              with:
                  token: ${{ secrets.REPO_GHA_PAT }}
                  repository: ${{ github.repository }}
                  event-type: build-and-cache-complete
                  client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
