name: Setup, build, cache
on:
    pull_request:
        paths-ignore:
            - '**/changelog/**'
description: Perform setup of dependencies and caches, performs repository_dispatch on completion.
permissions: {}

jobs:
    build-setup-cache:
        name: Setup dependencies, build, cache
        runs-on: ubuntu-20.04
        steps:
            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo

            - name: Trigger dependent workflows
              uses: peter-evans/repository-dispatch@v1
              with:
                  token: ${{ secrets.PAT_TOKEN_REPO_DISPATCH }}
                  repository: ${{ github.repository }}
                  event-type: build-and-cache-complete
                  client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
