name: 'Unit Tests'
on: 
  pull_request:
  push:
    branches:
      - 'trunk'
      - 'release/*'
concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true
jobs:
    build-ci-matrix:
      name: 'Build CI Matrix'
      runs-on: 'ubuntu-20.04'
      outputs:
        matrix: ${{ steps.build-ci-matrix.outputs.matrix }}
      steps:
        - uses: 'actions/checkout@v3'
          name: 'Checkout'
          with:
            fetch-depth: 0
        - uses: './.github/actions/setup-woocommerce-monorepo'
          name: 'Setup Monorepo'
          with:
            install: 'false'
        - uses: actions/github-script@v6
          id: 'build-ci-matrix'
          name: 'Build Matrix'
          with:
            script: |
              let baseRef = ${{ toJson( github.base_ref ) }};
              if ( baseRef ) {
                baseRef = 'origin/' + baseRef;
              }
              const buildCIMatrix = require( './.github/workflows/scripts/build-ci-matrix' );
              core.setOutput( 'matrix', JSON.stringify( buildCIMatrix( baseRef ) ) );
    project-task-matrix:
      name: '${{ matrix.projectName }} - ${{ matrix.taskName }}'
      runs-on: 'ubuntu-20.04'
      needs: 'build-ci-matrix'
      strategy:
        fail-fast: false
        matrix:
          include: ${{ fromJSON( needs.build-ci-matrix.outputs.matrix ) }}
      steps:
        - uses: 'actions/checkout@v3'
          name: 'Checkout'
        - uses: './.github/actions/setup-woocommerce-monorepo'
          name: 'Setup Monorepo'
          with:
            install-filters: ${{ matrix.projectName }}
            build-filters: ${{ matrix.projectName }}
        - name: 'Prepare Test Environment'
          if: ${{ matrix.needsTestEnvironment }}
          run: 'pnpm --filter="${{ matrix.projectName }}" test:env:start'
        - name: 'Test'
          if: ${{ matrix.runTests }}
          run: 'pnpm --filter="${{ matrix.projectName }}" test'
